config/routes.rb
FinanceClone::Application.routes.draw do
  get "static_pages/home"

  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do 
    resources :trades, :only => [:create]
    resources :recent_quotes, :only => [:create]
    resources :notifications, :only => [:create, :destroy]
    resources :follows, :only => [:create, :destroy, :index]
  end
  resource :session, :only => [:create, :destroy, :new]

  resources :companies, :only => [:show]
  
  resources :recent_quotes, :only => [:create]

  root :to => "static_pages#backbone"
  
  namespace :api, :defaults => { :format => :json } do
    resources :companies, :only => [:show, :index]
    resources :users, :only => [:show, :index]
    resources :trades, :only => [:show, :index, :create]
    resources :notifications, :only => [:show, :index, :create]
    resources :follows, :only => [:show, :index, :create, :destroy]
    resources :recent_quotes, :only => [:show, :index, :create]
    resources :notification_messages, :only => [:show, :index]
  end
end

  #   end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  has_many(
    :trades,
    class_name: "Trade",
    foreign_key: :user_id,
    dependent: :destroy
  )

  has_many(
    :recent_quotes,
    class_name: "RecentQuote",
    foreign_key: :user_id,
    dependent: :destroy
  )

  has_many(
    :notifications,
    class_name: "Notification",
    foreign_key: :user_id,
    dependent: :destroy
  )

  has_many(
    :notification_messages,
    class_name: "NotificationMessage",
    foreign_key: :user_id,
    dependent: :destroy
  )

  has_many(
    :follows,
    class_name: "Follow",
    foreign_key: :follower_id,
    dependent: :destroy
  )

  has_many(
    :users_they_follow,
    through: :follows,
    source: :leader
  )

  belongs_to(
    :leaders,
    class_name: "Follow",
    foreign_key: :leader_id,
  )

  def company_list
    #part of profit graph algorithm speed up
    list = []

    self.trades.each do |trade|
      company = Company.find(trade.company_id)
      list << company unless list.include?(company)
    end 

    list
  end

  def get_my_quotes

    # structure 
    # {company_id => company_quotes, etc ...}
 
    list = company_list
    result = {}

    list.each do |company|
      result[company.id] = company.quotes.order("id")
    end
    
    result
  end

  def profit_graph_data_hash
    data = {}

    return data if self.trades.length == 0

    my_quotes = get_my_quotes

    time = self.trades.first.created_at.time
    data[time] = 0

    #change time to 9:30 am est
    time = time.change(:hour => 14, :min => 30, :sec => 0)

    now = Time.new.getutc

    while true
      time += 1.day

      break if time > now

      data[time] = truncate(self.profit_date(time, my_quotes))
    end

    data[now] = self.profit

    return data
  end
   
  def follows?(user) 
    self.users_they_follow.include?(user)
  end


  def notification_value(company_id)
    notification = self.notifications.find_by_company_id(company_id)
    if notification.nil?
      0.0
    else
      notification.percent_swing
    end
  end

  def portfolio
    result = Hash.new(0)
    self.trades.each do |trade|
      result[trade.company_id] += trade.num_shares
    end     

    result.keys.each do |key|
      if result[key] == 0
        result.delete(key)
      end
    end

    result
  end

  # when calc profit/ percent
  # don't use portfolio table, use transaction history
  #do algorithm to temp add closing positions then use 
  #equations for profit/percent 

  def profit
    temp_trades = get_temp_trades

    result = 0
    temp_trades.each do |trade|
      result -= trade.num_shares * trade.price
    end

    truncate_round(result)
  end

  def profit_date(time, my_quotes)
    temp_trades = get_temp_trades_date(time, my_quotes)

    result = 0
    temp_trades.each do |trade|
      result -= trade.num_shares * trade.price
    end

    result
  end

  def percent_gain
    temp_trades = get_temp_trades

    numer = 0
    denom = 0

    temp_trades.each do |trade|
      value = trade.num_shares * trade.price

      if trade.num_shares < 0
        numer -= value
      else
        denom += value
      end
    end
    
    if denom == 0
      0
    else
      truncate(((numer / denom) - 1) * 100)
    end
  end

  #auth

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def get_temp_trades
    #copy trades 
    result = []
    self.trades.each { |trade| result.push(trade) }

    # temporarily close all positions
    self.portfolio.keys.each do |company_id|
      result.push(
        Trade.new(
          user_id: self.id,
          company_id: company_id, 
          num_shares: -self.portfolio[company_id], 
          price: Company.find(company_id).quotes.order("id").last.price
        )
      )
    end

    result
  end

  def truncate(x)
    (x * 100).floor / 100.0
  end

    def truncate_round(x)
    (x * 100).round / 100.0
  end

  def get_temp_trades_date(time, my_quotes)
    #copy trades 
    result = []
    self.trades.each do |trade| 
      trade_time = trade.created_at.time
      break if trade_time > (time)
      result.push(trade) 
    end

    # temporarily close all positions
    my_portfolio = get_temp_portfolio(time)

    my_portfolio.keys.each do |company_id|

      my_quotes_company = my_quotes[company_id] #part of profit graph algorithm speed up

      result.push(
        Trade.new(
          user_id: self.id,
          company_id: company_id, 
          num_shares: -my_portfolio[company_id], 
          price: Company.find_price_from_day(time, my_quotes_company)
        )
      )
    end

    result
  end

  def get_temp_portfolio(time)
    result = Hash.new(0)
    self.trades.each do |trade|
      trade_time = trade.created_at.time
      break if trade_time > (time)
      result[trade.company_id] += trade.num_shares
    end     

    result.keys.each do |key|
      if result[key] == 0
        result.delete(key)
      end
    end

    result
  end


end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @trades_company_id = []
    @trades_num_shares = []
    @trades_price = []
    @user.trades.each do |trade|
	  @trades_company_id.push(trade.company_id)
	  @trades_num_shares.push(trade.num_shares)
	  @trades_price.push(trade.price)
    end

    render "show"
  end

  def index
    @users = User.all
    render "index"
    #render json: @users
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
    render :new, :layout => false
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      #redirect_to user_url(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, :layout => false
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def edit
    @user = current_user
    unless params.include?(:id) && current_user.id == params[:id].to_i     
      redirect_to user_url(current_user)
    end
    render :edit, :layout => false
  end
  
  def update
    @user = current_user
    if params.include?(:id) && current_user.id == params[:id].to_i && @user.update_attributes(user_update_params)
      #redirect_to user_url(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def index
    @users = User.all
    @users.sort! { |a,b| b.percent_gain <=> a.percent_gain }
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
  def user_update_params
      params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance Clone</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
    
    <%= csrf_meta_tags %>
    
</head>
<body  class="sign-in">


<form action="<%= user_url(@user) %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="put">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_name">Name</label>
  <br>
  <input
     id="user_name"
     name="user[name]"
     type="text"
     value="<%= @user.name %>">
  <br><br>

  <label for="user_email">Email</label>
  <br>
  <input
     id="user_email"
     name="user[email]"
     type="text"
     value="<%= @user.email %>">
  <br><br>

  <input type="submit" value="Save" class="btn btn-default">
</form>

</body>
</html>

app/views/users/index.html.erb
<h2> Leaderboard </h2> &nbsp;&nbsp;&nbsp;

<% if signed_in? %>
  <a href="<%= user_follows_url(current_user) %>" class="btn btn-default">show followed only</a>
<% end %>

<br><br>

<table class="table table-condensed">
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td>
      	 <%= "+" if user.percent_gain > 0 %><%= user.percent_gain %>&#37;
      </td>
      <td><b><a href="<%= user_url(user) %>"><span>i</span></a></b></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bitChart.co</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
    
    <%= csrf_meta_tags %>
    
</head>
<body class="sign-in">




<h1><font color="blue" face="verdana"><i>bit</i></font><font color="green">Chart</font><font color="orange">.</font></font><font color="red"><i>co</i></font></h1>

<%= link_to "Sign In", new_session_url %> |
<%= link_to "Sign up", new_user_url %>

<br><br>

<form action="<%= users_url %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input
     id="user_name"
     name="user[name]"
     type="text"
     placeholder="Name">
  <br>

  <input
     id="user_email"
     name="user[email]"
     type="text"
     placeholder="Email">
  <br>

  <input
     id="user_password"
     name="user[password]"
     type="password"
     placeholder="Password">
  <br><br>

  <input type="submit" value="Sign up" class="btn btn-default">
</form>


    <!-- Errors - start -->
    <% if flash[:errors] %>
    <br><br><hr>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <br>
    
    <% end %>
    <!-- Errors - end -->


</body>
</html>

app/views/users/show.html.erb
<h2>
  <%= (signed_in? && current_user.id == @user.id) ? "My" : (@user.name + "'s") %> 
  Portfolio
</h2>&nbsp;&nbsp;&nbsp;

<!-- follow or unfollow - start -->
<% if signed_in? && current_user.id != @user.id %>

  <% if current_user.follows?(@user) %>
    <% follow = Follow.where(follower_id: current_user.id, leader_id: @user.id)[0] %>
  <% end %>

  <% action = (current_user.follows?(@user) ? user_follow_url(current_user.id, follow.id) : user_follows_url(current_user)) %>
  <% method = (current_user.follows?(@user) ? "delete" : "post") %>
  <% message = (current_user.follows?(@user) ? "Unfollow" : "Follow") %>

  <form action="<%= action %>" method="post">
    <input
      name="_method"
      type="hidden"
      value="<%= method %>">
    <input
      name="authenticity_token"
      type="hidden"
      value="<%= form_authenticity_token %>">
    <input
      id="follow_leader_id"
      name="follow[leader_id]"
      type="hidden"
      value="<%= @user.id %>">
    <input type="submit" value="<%= message %>" class="btn btn-default">
  </form>
<% end %>
<!-- follow or unfollow - end -->

<br><br>

<!-- profit percent gain - start -->
<font color="<%= (@user.profit < 0) ? "red" : "green" %>" size="4">
  <%= "▲" if @user.profit > 0 %>
  <%= "▼" if @user.profit < 0 %>
  &#36;<%= @user.profit.abs %>
  (<%= @user.percent_gain.abs %>&#37;)
</font>
<!-- profit percent gain - end -->

<br><br>

<!-- Portfolio - start -->
<% flag = signed_in? && current_user.id == @user.id %>
<table class="table table-striped table-bordered table-condensed">
  <th>Name</th>
  <th>Symbol</th>
  <th>Price</th>
  <th>Change</th>
  <th>Position</th>
  <% if flag %> 
    <th>Notification</th>
  <% end %>
  <% @user.portfolio.keys.each do |company_id| %>
    <tr>

      <% company = Company.find(company_id) %>
      <% quote = company.quotes.last %>

      <td><%= company.name %></td>

      <td><%= company.symbol %></td>

      <td><%= quote.price %></td>
      
      <td>
      <font color="<%= (quote.change < 0) ? "red" : "green" %>">
        <%= "+" if (quote.change > 0) %><%= quote.change %> (<%= quote.percent_change %>&#37;)
      </font>
      </td>

      <td><%= @user.portfolio[company_id] %></td>

      <% if flag %> 
        <td>
          <form action="<%= user_notifications_url(@user) %>" method="post">

            <input
              name="authenticity_token"
              type="hidden"
              value="<%= form_authenticity_token %>">

            <input
              id="notification-company_id"
              name="notification[company_id]"
              type="hidden"
              value="<%= company_id %>">

            <input
              id="notification-percent_swing"
              name="notification[percent_swing]"
              type="text"
              value="<%= @user.notification_value(company_id) %>">

            <input type="submit" value="Set">
            
          </form>
        </td>
      <% end %>

    </tr>
  <% end %>
</table>
<!-- Portfolio - end -->

<br>

<!-- Transactions - start -->
<h2>Transactions</h2><br><br>

<table class="table table-striped table-bordered table-condensed">
  <th>Company</th>
  <th>Number of Shares</th>
  <th>Price</th>
  <% @user.trades.each do |trade| %>
    <tr>
      <td><%= Company.find(trade.company_id).symbol %></td>
      <td><%= trade.num_shares %></td>
      <td><%= trade.price %></td>
    </tr>
  <% end %>
</table>

<% if signed_in? && current_user.id == @user.id %>
<form action="<%= user_trades_url(@user) %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="trade_symbol">symbol:</label>
  <input
     id="trade_symbol"
     name="trade[symbol]"
     type="text">
  &nbsp;&nbsp;&nbsp;
  <label for="trade_num_shares">&#35; of shares:</label>
  <input
     id="trade_num_shares"
     name="trade[num_shares]"
     type="text">
  &nbsp;&nbsp;&nbsp;
  <input type="submit" value="Trade" class="btn btn-default">
</form>
<% end %>

<!-- Transactions - end -->

<br><br>

<!-- Performance graph - start -->
<h2> Performance </h2>
<% data = @user.profit_graph_data_hash %>
<% unless data.values.empty? %>
  <% diff = (data.values.max - data.values.min) / 10.0 %>
  <%= line_chart(data, min: data.values.min - diff, max: data.values.max +  diff, height: "400px") %>
<% end %>

<!-- Performance graph - end -->