config/routes.rb
FinanceClone::Application.routes.draw do
  get "static_pages/home"

  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do 
    resources :trades, :only => [:create]
    resources :recent_quotes, :only => [:create]
    resources :notifications, :only => [:create, :destroy]
    resources :follows, :only => [:create, :destroy, :index]
  end
  resource :session, :only => [:create, :destroy, :new]

  resources :companies, :only => [:show]
  
  resources :recent_quotes, :only => [:create]

  root :to => "static_pages#backbone"
  
  namespace :api, :defaults => { :format => :json } do
    resources :companies, :only => [:show, :index]
    resources :users, :only => [:show, :index]
    resources :trades, :only => [:show, :index, :create]
    resources :notifications, :only => [:show, :index, :create]
    resources :follows, :only => [:show, :index, :create, :destroy]
    resources :recent_quotes, :only => [:show, :index, :create]
    resources :notification_messages, :only => [:show, :index]
  end
end

  #   end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bitChart.co</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
    <%= stylesheet_link_tag 'custom.css' %>
    
    <%= csrf_meta_tags %>
    
  </head>

<header>


  <nav class="group">
    <h2 class="logo"><font color="blue" face="verdana"><i>bit</i></font><font color="green">Chart</font><font color="orange">.</font></font><font color="red"><i>co</i></font></h2>
    <!-- Get a quote - start -->
    <% action = (signed_in? ? user_recent_quotes_url(current_user) : recent_quotes_url) %>    
    <form action="<%= action  %>" method="post" class="get-quote">
      <input
        name="authenticity_token"
        type="hidden"
        value="<%= form_authenticity_token %>">

      <input
        id="recent_quote_symbol"
        name="recent_quote[symbol]"
        type="text"
        placeholder="enter stock ticker">

      <input type="submit" value="Search" class="btn btn-default">
    </form>
    <!-- Get a quote - end -->
    <ul>
      <li class="dropdown">
        <a>Alerts</a>

        <% if signed_in? %>
        <% @notification_messages = current_user.notification_messages %>
        <% if @notification_messages.length > 5 %>
          <% @notification_messages = @notification_messages[-5..-1] %>
        <% end %>
        <ul class="menu">
          <% @notification_messages.reverse.each do |msg| %>
            <li><%= msg.message %></li>
          <% end %>
        </ul>
        <% end %>

      </li>
      <li class="dropdown">
        <a>Account</a>

        <ul class="menu-account">
          <li>
          <% if signed_in? %>
    Signed in as: <%= current_user.email %>
          <% end %>
          </li>
          
          <li>
<!-- Edit Account - start -->
    <% if signed_in? %>
    <ul class="list-inline">
      <li><%= link_to "Edit Account", edit_user_url(current_user), class: "btn btn-default" %></li>
      <li><%= button_to "Sign Out", session_url, :method => :delete, class: "btn btn-default" %></li>
    </ul>
    <% else %>
    <p>
      <%= link_to "Sign In", new_session_url, class: "btn btn-default" %> 
      <%= link_to "Sign up", new_user_url, class: "btn btn-default" %>
    </p>
    <% end %>
    <!-- Edit Account - end -->
          </li>
        </ul>

      </li>
    </ul>
  </nav>
</header>

<!-- end of nav bar -->

  <body>

    <!-- Errors - start -->
    <% if flash[:errors] %>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <br>
    <hr>
    <% end %>
    <!-- Errors - end -->


<div class="row main-row">

  <div class="col-xs-3 col-sidebar">
    <!-- Home menu - start -->
    <br>
    <a href="/static_pages/home" class="">Home</a> <br>
    <% if signed_in? %>
    <a href="<%= user_url(current_user) %>">My Portfolio</a> <br>
    <% end %>
    <a href="<%= users_url %>">Leaderboard</a>

    <!-- Home menu - end -->
    <hr>



    <!-- Recent quotes - start -->
    <% if signed_in? %>
      Recent Quotes<br><br>

      <table class="table table-condensed">
        <% counter = 0 %>
        <% current_user.recent_quotes.reverse.each do |quote| %>
          <tr>
            <td>
              <% company = Company.find(quote.company_id)%>

              <form action="<%= user_recent_quotes_url(current_user)  %>" method="post">
                <input
                  name="authenticity_token"
                  type="hidden"
                  value="<%= form_authenticity_token %>">

                <input
                  id="recent_quote_symbol"
                  name="recent_quote[symbol]"
                  type="hidden"
                  value="<%= company.symbol %>">

                <input type="submit" value="<%= company.symbol %>" class="btn-link">
              </form>

            </td>
            <% quote = company.quotes.last %>
            <td><div class="recent-quote-price-change"><%= quote.price %></div></td>
            <td><div class="recent-quote-price-change">
              <font color="<%= (quote.change < 0) ? "red" : "green" %>">
              <%= "+" if quote.change > 0 %><%= quote.change %>
            </font></div>
            </td>
          </tr>
          <% counter += 1 %>
          <% break if counter == 10 %>
        <% end %>
      </table>

    <% end %>
    <!-- Recent quotes - end -->
  </div>

  <div class="col-xs-9 col-mainbar">
    <br>
    <%= yield %>
  </div>

</div>

  </body>
</html>